project:
  type: website
  output-dir: docs

website:
  favicon: images/penguin.png
  page-footer: "Copyright 2023, Jürgen Wilbert"
  search: true
  navbar:
    #logo: images/penguin.png
    left:
      - projects.qmd
      - publications.qmd
      - rpackages.qmd
      - students.qmd
      - links.qmd
      - text: "Courses"
        menu:
          - text: "Single-case regression analzes"
            href: https://jazznbass.github.io/workshop_scan_regression/
      - blog.qmd
        
    right:
      - icon: github
        href: https://github.com/jazznbass
      - icon: researchgate
        href: https://www.researchgate.net/profile/Juergen_Wilbert2


format:
  html:
    theme: [sandstone]
    highlight: tango
    css: style_add.css
    page-layout: full

    



