project:
  type: website
  output-dir: docs

website:
  favicon: images/penguin.png
  page-footer: "&#169; Jürgen Wilbert, last updated 2025-05-07"
  search: true
  navbar:
    alignment: center
    #logo: images/penguin.png
    left:
      - text: "Home"
        file: "index.qmd"
      - text: "Projects"
        file: "projects.qmd"
      - text: "Publications"
        file: "publications.qmd"
      - text: "Software"
        file: "rpackages.qmd"
      - text: "Graduate Students"
        file: "students.qmd"
      #- text: "Links"
      #  file: "links.qmd"
      - text: "Private Blog"
        file: blog.html
    right:
      - icon: github
        href: https://github.com/jazznbass
      - icon: researchgate
        href: https://www.researchgate.net/profile/Juergen_Wilbert2


format:
  html:
    theme: [sandstone]
    highlight: tango
    css: style_add.css


    



