project:
  type: website
  output-dir: docs

website:
  favicon: images/penguin.png
  page-footer: "&#169; Jürgen Wilbert, last updated 2024-12-11"
  search: true
  navbar:
    #logo: images/penguin.png
    left:
      - text: "Home"
        file: "index.qmd"
      - text: "Projects"
        file: "projects.qmd"
      - text: "Publications"
        file: "publications.qmd"
      - text: "Software"
        file: "rpackages.qmd"
      - text: "Graduate Students"
        file: "students.qmd"
      - text: "Links"
        file: "links.qmd"
      #- text: "Courses"
      #  menu:
      #    - text: "Single-case regression analzes"
      #      href: https://jazznbass.github.io/workshop_scan_regression/
      - blog.qmd
        
    right:
      - icon: github
        href: https://github.com/jazznbass
      - icon: researchgate
        href: https://www.researchgate.net/profile/Juergen_Wilbert2


format:
  html:
    theme: [sandstone]
    highlight: tango
    css: style_add.css
    page-layout: full

    



