---
title: 'Create Rmarmdown webpage on gitHub'
author: Jürgen Wilbert
date: '2021-04-19'
abstract: 'Short description how to create an Rmarkdown webpage and publish it on gitHub'
keywords: 
  - Rmarkdown
  - GitHub
  - RStudio
  - Webpage
output:
  html_document: 
    toc: yes
    toc_depth: 2
    toc_float: yes
    df_print: default 
    theme: yeti
---

```{r results='asis', echo = FALSE}
cat("***  \n", "*Keywords: ", paste0(rmarkdown::metadata$keywords, collapse = ", "), "*  \n"
)
```

***

1. Create a new R Project: \
  `File -> New Project -> New Directory -> Simple Rmarkdown website`
2. Open new project
3. Activate "git" versioning for this project (`tools -> project Options -> Git/SVN`)
3. Edit the YAML file `_site.yml`: \
  add the line: `output_dir: "docs"``
4. Build website: `Build -> Build all`
5. Change to Github Desktop
6. Add repository: `File -> Add local repository`
7. Click: Publish repository
8. Open Github in Webbrowser and login
9. Go to the new published repository
10. Click `Settings``
11. Go to menu `Pages` or scroll to Github Pages
12. At the field "Source" select `master`
13. Change `select folder` from `\(root)` to `\docs`
14. click save
15. Copy / remember / open the link to the new webpage that opens up!
16 Change to Webpage project at RStudio
17. Commit **and** publish all files `[tab] Git -> Commit`
18. Change to the new webpage address you remembered/copied or opened! (probably wait 30 seconds and renew the page)

That's it!




